In [1]:
"""
Task 1: Train and Evaluate Machine Learning Models
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../data/scored_leads.csv')

In [3]:
df.columns

Index(['Company Name', 'Website', 'Country', 'Industry', 'website_exists',
       'contact_form', 'contact_page_exists', 'services_count',
       'country_score', 'industry_score', 'lead_quality_score',
       'total_lead_score', 'Lead Score', 'Predicted Lead Class'],
      dtype='object')

In [4]:
# Features (X) and Target (y)
features = ['website_exists', 'contact_form', 'services_count', 'country_score']
X = df[features]
y = df['Predicted Lead Class']

In [5]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training samples: {len(X_train)}")
print(f"Testing samples: {len(X_test)}")

Training samples: 40
Testing samples: 10


In [ ]:
models = {
    'Decision Tree': DecisionTreeClassifier(
    max_depth=3,              # depth limit (decrease if overfitting)
    min_samples_split=15,     # increase for less overfitting
    min_samples_leaf=8,       # increase for less overfitting
    max_features='sqrt',      # limit features
    random_state=42
),

    'Random Forest': RandomForestClassifier(
    n_estimators=30,          # kam trees (fast training)
    max_depth=3,              # depth limit
    min_samples_split=15,     # increase
    min_samples_leaf=8,       # increase
    max_features='sqrt',
    random_state=42
),

    'Logistic Regression': LogisticRegression(
        random_state=42,
        max_iter=1000
    )
}

In [ ]:
# Train and evaluate
results = []

for name, model in models.items():
    # Train
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Evaluate
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    results.append({
        'Model': name,
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1 Score': f1
    })

    print(f"\n{name}")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1:.4f}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))


Decision Tree
Accuracy: 0.6000
Precision: 1.0000
Recall: 0.6000
F1 Score: 0.7500
Confusion Matrix:
[[0 0]
 [4 6]]

Random Forest
Accuracy: 0.7000
Precision: 1.0000
Recall: 0.7000
F1 Score: 0.8235
Confusion Matrix:
[[0 0]
 [3 7]]

Logistic Regression
Accuracy: 0.7000
Precision: 1.0000
Recall: 0.7000
F1 Score: 0.8235
Confusion Matrix:
[[0 0]
 [3 7]]


c:\Users\hamza\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\hamza\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\hamza\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metri

In [8]:
# Results table
results_df = pd.DataFrame(results)
print("\n" + "="*50)
print("Model Comparison Summary")
print("="*50)
print(results_df.to_string(index=False))

# Best model
best_model = results_df.loc[results_df['F1 Score'].idxmax(), 'Model']
print(f"\n🏆 Best Model: {best_model}")


Model Comparison Summary
              Model  Accuracy  Precision  Recall  F1 Score
      Decision Tree       0.6        1.0     0.6  0.750000
      Random Forest       0.7        1.0     0.7  0.823529
Logistic Regression       0.7        1.0     0.7  0.823529

🏆 Best Model: Random Forest


In [9]:
import joblib
import os

# Save model
os.makedirs('saved_models', exist_ok=True)
joblib.dump(best_model, 'saved_models/best_model.pkl')
print(f"\n✅ Model saved to: saved_models/best_model.pkl")

# Save feature names (important for prediction)
os.makedirs('saved_encoders', exist_ok=True)
joblib.dump(features, 'saved_encoders/feature_names.pkl')
print(f"✅ Feature names saved to: saved_encoders/feature_names.pkl")


✅ Model saved to: saved_models/best_model.pkl
✅ Feature names saved to: saved_encoders/feature_names.pkl
